{% set version = "0.4.0" %}

package:
  name: robotframework-jupyterlibrary
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/r/robotframework-jupyterlibrary/robotframework-jupyterlibrary-{{ version }}.tar.gz
  sha256: 15b90dd2501dd76624851003ab819679470af1db82da389df933be2f2cb9eae8

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv --no-deps

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - python >=3.6
    - robotframework >=3.2
    - robotframework-seleniumlibrary >=4.5

test:
  requires:
    - pip
  imports:
    - JupyterLibrary
  commands:
    - pip check

about:
  home: https://github.com/robots-from-jupyter/{{ name }}
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: A Robot Framework library for testing Jupyter end-user applications and extensions
  doc_url: https://{{ name }}.readthedocs.io
  dev_url: https://github.com/robots-from-jupyter/{{ name }}
  doc_source_url: https://github.com/robots-from-jupyter/{{ name }}/tree/master/docs

extra:
  recipe-maintainers:
    - martinRenou
    - bollwyvl
