{% set version = "0.4.2" %}

package:
  name: robotframework-jupyterlibrary
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/r/robotframework-jupyterlibrary/robotframework-jupyterlibrary-{{ version }}.tar.gz
  sha256: 238bb98293249694a1b28d5bc8ebe930a38bfde42222fba0a80475f33b00571f

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv --no-deps

requirements:
  host:
    - pip
    - python >=3.7
  run:
    - python >=3.7
    - robotframework >=4
    - robotframework-seleniumlibrary >=4.5

test:
  requires:
    - pip
  imports:
    - JupyterLibrary
  commands:
    - pip check

about:
  home: https://github.com/robots-from-jupyter/robotframework-jupyterlibrary
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: A Robot Framework library for testing Jupyter end-user applications and extensions
  doc_url: https://robotframework-jupyterlibrary.readthedocs.io
  dev_url: https://github.com/robots-from-jupyter/robotframework-jupyterlibrary
  doc_source_url: https://github.com/robots-from-jupyter/robotframework-jupyterlibrary/tree/v{{ version }}/docs

extra:
  recipe-maintainers:
    - martinRenou
    - bollwyvl
