{% set name = "robotframework-jupyterlibrary" %}
{% set version = "0.3.1" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: b42446502e90e8322153d67e2a3f18ca05913d17b91ee6b3b824dcb86e0f5d4b

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv --no-deps

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - ipython
    - python >=3.6
    - robotframework >=3.2
    - robotframework-seleniumlibrary >=4.5

test:
  requires:
    - pip
  imports:
    - JupyterLibrary
  commands:
    - pip check

about:
  home: https://github.com/robots-from-jupyter/{{ name }}
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: A Robot Framework library for testing Jupyter end-user applications and extensions
  doc_url: https://{{ name }}.readthedocs.io
  dev_url: https://github.com/robots-from-jupyter/{{ name }}
  doc_source_url: https://github.com/robots-from-jupyter/{{ name }}/tree/master/docs

extra:
  recipe-maintainers:
    - martinRenou
    - bollwyvl
