{% set version = "0.5.0" %}

package:
  name: robotframework-jupyterlibrary
  version: {{ version }}

source:
  url:  https://pypi.io/packages/source/r/robotframework-jupyterlibrary/robotframework_jupyterlibrary-{{ version }}.tar.gz
  sha256: f9e0aceebb5c8e22d9020d157b36432e0ba8fc32076bc01e362880a7f5ee6cab

build:
  noarch: python
  number: 1
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - pip
    - python {{ python_min }}
    - flit >=3.9,<4
  run:
    - python >={{ python_min }}
    - robotframework >=5
    - robotframework-seleniumlibrary >=4.5

test:
  requires:
    - pip
    - python {{ python_min }}
  imports:
    - JupyterLibrary
  commands:
    - pip check

about:
  home: https://github.com/robots-from-jupyter/robotframework-jupyterlibrary
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: A Robot Framework library for testing Jupyter end-user applications and extensions
  doc_url: https://robotframework-jupyterlibrary.readthedocs.io
  doc_source_url: https://github.com/robots-from-jupyter/robotframework-jupyterlibrary/tree/v{{ version }}/docs

extra:
  recipe-maintainers:
    - martinRenou
    - bollwyvl
